name: Build and Test
on:
  push:
    branches: [ humble ]
  pull_request:
    branches: [ humble ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Pre install
        run: |
          /usr/bin/bash -c "apt-get update && apt-get install -y libunwind-dev libceres-dev"
      - name: Build
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          skip-tests: true
      - name: Remove flake8-quotes flake8-import-order for linter
        run: pip3 uninstall -y flake8-quotes flake8-import-order
      - name: Test calibration_interfaces
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh calibration_interfaces
      - name: Test calibration_common
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh calibration_common
      - name: Test camera_intrinsic_calibration
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh camera_intrinsic_calibration
